# -*- coding: utf-8 -*-
"""Sentence Transformers

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LzJrRYKhQo0_b-zsg8ZUgzgukxTUdqLF
"""

from sentence_transformers import SentenceTransformer, util
# load the model
model = SentenceTransformer('all-MiniLM-L6-v2') # Corrected model name and class
#take input from users
text_1 = input("enter text 1:") # Corrected variable name
text_2 = input("enter text 2:") # Corrected variable name
#convert text to embeddings
embedding_1 = model.encode(text_1) # Corrected variable name and method call
embedding_2 = model.encode(text_2) # Corrected variable name and method call
#calculate similarity
similarity = util.cos_sim(embedding_1, embedding_2) # Corrected variable names
#show result
print("\n similarity score:", round(float(similarity), 2)) # Corrected round function arguments
if similarity > 0.75:
  print("similarity level:high")
elif similarity > 0.5:
  print("similarity level:medium")
else:
  print("similarity level:low")