# -*- coding: utf-8 -*-
"""Text Generation Code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oiHNV2Z-VKysc5Ryahp6mOvNTA96TSFr
"""

!pip install transformers torch

from transformers import pipeline

#Load text generation model(GenAI)
generator =pipeline("text-generation",model="gpt2")

#Input prompt
prompt="Aritificial Intelligence in finance will"

#Generate text
result=generator(prompt,max_length=50,num_return_sequences=1)

print("AI generated Text:")
print(result[0]['generated_text'])