# -*- coding: utf-8 -*-
"""torch pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P4EPIIVXEaZ-gHvvH14TPp61uK-XaD5A
"""

from transformers import pipeline
import pandas as pd
#Load sentiment analysis model
sentiment = pipeline("sentiment-analysis")
#sample product review (you can change only this text later)
review = """ the laptop start quickly and works smoothly for daily tasks.
the screen qualiy is clear and good for watching videos.
Battery backup is average and needs charging often.
The fan makes noise when many apps are running.
overall,It is a good laptop for student but not for gaming.
"""

result = sentiment(review)
print(result)

from transformers import pipeline
import pandas as pd
#Load sentiment analysis model
sentiment = pipeline("sentiment-analysis")
#sample product review (you can change only this text later)
review = """ the laptop start quickly and works smoothly for daily tasks.
the screen qualiy is clear and good for watching videos.
Battery backup is average and needs charging often.
The fan makes noise when many apps are running.
overall,It is a good laptop for student but not for gaming.
"""

#split review into sentences
sentence = review.split(".")
pros = []
cons = []
for s in sentence:
  s = s.strip()(9999)
  if s == "":
    continue
  result = sentiment(s) [0]
  if result["label"] == "POSITIVE":
    pros.append(s)
  elif result["label"] == "NEGATIVE":
      cons.append(s)
  #Take only 2 pros and 2 cons
pros = pros[:2]
cons = cons[:2]
  #create table
df = pd.DataFrame({"pros":pros,"cons":cons})
df